export interface Capital {
  capital: string;
  country: string;
  longitude: number;
  latitude: number;
}

/**
 * All 193 UN member states (as of February 2026) with their capitals.
 * Sorted alphabetically by country name.
 */
export const CAPITALS: Capital[] = [
  { capital: 'Kabul', country: 'Afghanistan', longitude: 69.17, latitude: 34.53 },
  { capital: 'Tirana', country: 'Albania', longitude: 19.82, latitude: 41.33 },
  { capital: 'Algiers', country: 'Algeria', longitude: 3.04, latitude: 36.77 },
  { capital: 'Andorra la Vella', country: 'Andorra', longitude: 1.52, latitude: 42.51 },
  { capital: 'Luanda', country: 'Angola', longitude: 13.23, latitude: -8.84 },
  { capital: "Saint John's", country: 'Antigua and Barbuda', longitude: -61.85, latitude: 17.12 },
  { capital: 'Buenos Aires', country: 'Argentina', longitude: -58.38, latitude: -34.6 },
  { capital: 'Yerevan', country: 'Armenia', longitude: 44.51, latitude: 40.18 },
  { capital: 'Canberra', country: 'Australia', longitude: 149.13, latitude: -35.28 },
  { capital: 'Vienna', country: 'Austria', longitude: 16.37, latitude: 48.21 },
  { capital: 'Baku', country: 'Azerbaijan', longitude: 49.87, latitude: 40.41 },
  { capital: 'Nassau', country: 'Bahamas', longitude: -77.34, latitude: 25.06 },
  { capital: 'Manama', country: 'Bahrain', longitude: 50.58, latitude: 26.23 },
  { capital: 'Dhaka', country: 'Bangladesh', longitude: 90.41, latitude: 23.71 },
  { capital: 'Bridgetown', country: 'Barbados', longitude: -59.62, latitude: 13.1 },
  { capital: 'Minsk', country: 'Belarus', longitude: 27.57, latitude: 53.9 },
  { capital: 'Brussels', country: 'Belgium', longitude: 4.35, latitude: 50.85 },
  { capital: 'Belmopan', country: 'Belize', longitude: -88.77, latitude: 17.25 },
  { capital: 'Porto-Novo', country: 'Benin', longitude: 2.62, latitude: 6.5 },
  { capital: 'Thimphu', country: 'Bhutan', longitude: 89.64, latitude: 27.47 },
  { capital: 'Sucre', country: 'Bolivia', longitude: -65.26, latitude: -19.04 },
  { capital: 'Sarajevo', country: 'Bosnia and Herzegovina', longitude: 18.41, latitude: 43.86 },
  { capital: 'Gaborone', country: 'Botswana', longitude: 25.91, latitude: -24.65 },
  { capital: 'Brasília', country: 'Brazil', longitude: -47.88, latitude: -15.79 },
  { capital: 'Bandar Seri Begawan', country: 'Brunei', longitude: 114.95, latitude: 4.94 },
  { capital: 'Sofia', country: 'Bulgaria', longitude: 23.32, latitude: 42.7 },
  { capital: 'Ouagadougou', country: 'Burkina Faso', longitude: -1.52, latitude: 12.37 },
  { capital: 'Gitega', country: 'Burundi', longitude: 29.93, latitude: -3.43 },
  { capital: 'Praia', country: 'Cabo Verde', longitude: -23.51, latitude: 14.93 },
  { capital: 'Phnom Penh', country: 'Cambodia', longitude: 104.92, latitude: 11.56 },
  { capital: 'Yaoundé', country: 'Cameroon', longitude: 11.52, latitude: 3.87 },
  { capital: 'Ottawa', country: 'Canada', longitude: -75.7, latitude: 45.42 },
  { capital: 'Bangui', country: 'Central African Republic', longitude: 18.56, latitude: 4.36 },
  { capital: "N'Djamena", country: 'Chad', longitude: 15.04, latitude: 12.11 },
  { capital: 'Santiago', country: 'Chile', longitude: -70.67, latitude: -33.45 },
  { capital: 'Beijing', country: 'China', longitude: 116.41, latitude: 39.9 },
  { capital: 'Bogotá', country: 'Colombia', longitude: -74.07, latitude: 4.71 },
  { capital: 'Moroni', country: 'Comoros', longitude: 43.26, latitude: -11.7 },
  { capital: 'Brazzaville', country: 'Congo', longitude: 15.28, latitude: -4.27 },
  { capital: 'San José', country: 'Costa Rica', longitude: -84.09, latitude: 9.93 },
  { capital: 'Yamoussoukro', country: "Côte d'Ivoire", longitude: -5.28, latitude: 6.82 },
  { capital: 'Zagreb', country: 'Croatia', longitude: 15.98, latitude: 45.81 },
  { capital: 'Havana', country: 'Cuba', longitude: -82.37, latitude: 23.11 },
  { capital: 'Nicosia', country: 'Cyprus', longitude: 33.38, latitude: 35.17 },
  { capital: 'Prague', country: 'Czechia', longitude: 14.42, latitude: 50.08 },
  { capital: 'Kinshasa', country: 'Democratic Republic of the Congo', longitude: 15.27, latitude: -4.32 },
  { capital: 'Copenhagen', country: 'Denmark', longitude: 12.57, latitude: 55.68 },
  { capital: 'Djibouti', country: 'Djibouti', longitude: 43.15, latitude: 11.59 },
  { capital: 'Roseau', country: 'Dominica', longitude: -61.39, latitude: 15.3 },
  { capital: 'Santo Domingo', country: 'Dominican Republic', longitude: -69.93, latitude: 18.48 },
  { capital: 'Quito', country: 'Ecuador', longitude: -78.47, latitude: -0.18 },
  { capital: 'Cairo', country: 'Egypt', longitude: 31.24, latitude: 30.04 },
  { capital: 'San Salvador', country: 'El Salvador', longitude: -89.19, latitude: 13.69 },
  { capital: 'Malabo', country: 'Equatorial Guinea', longitude: 8.78, latitude: 3.75 },
  { capital: 'Asmara', country: 'Eritrea', longitude: 38.93, latitude: 15.34 },
  { capital: 'Tallinn', country: 'Estonia', longitude: 24.75, latitude: 59.44 },
  { capital: 'Mbabane', country: 'Eswatini', longitude: 31.13, latitude: -26.32 },
  { capital: 'Addis Ababa', country: 'Ethiopia', longitude: 38.75, latitude: 9.02 },
  { capital: 'Suva', country: 'Fiji', longitude: 178.44, latitude: -18.14 },
  { capital: 'Helsinki', country: 'Finland', longitude: 24.94, latitude: 60.17 },
  { capital: 'Paris', country: 'France', longitude: 2.35, latitude: 48.86 },
  { capital: 'Libreville', country: 'Gabon', longitude: 9.45, latitude: 0.39 },
  { capital: 'Banjul', country: 'Gambia', longitude: -16.58, latitude: 13.45 },
  { capital: 'Tbilisi', country: 'Georgia', longitude: 44.79, latitude: 41.72 },
  { capital: 'Berlin', country: 'Germany', longitude: 13.41, latitude: 52.52 },
  { capital: 'Accra', country: 'Ghana', longitude: -0.19, latitude: 5.56 },
  { capital: 'Athens', country: 'Greece', longitude: 23.73, latitude: 37.98 },
  { capital: "St. George's", country: 'Grenada', longitude: -61.75, latitude: 12.05 },
  { capital: 'Guatemala City', country: 'Guatemala', longitude: -90.53, latitude: 14.63 },
  { capital: 'Conakry', country: 'Guinea', longitude: -13.68, latitude: 9.54 },
  { capital: 'Bissau', country: 'Guinea-Bissau', longitude: -15.6, latitude: 11.86 },
  { capital: 'Georgetown', country: 'Guyana', longitude: -58.16, latitude: 6.8 },
  { capital: 'Port-au-Prince', country: 'Haiti', longitude: -72.34, latitude: 18.54 },
  { capital: 'Tegucigalpa', country: 'Honduras', longitude: -87.22, latitude: 14.08 },
  { capital: 'Budapest', country: 'Hungary', longitude: 19.04, latitude: 47.5 },
  { capital: 'Reykjavik', country: 'Iceland', longitude: -21.9, latitude: 64.14 },
  { capital: 'New Delhi', country: 'India', longitude: 77.21, latitude: 28.61 },
  { capital: 'Jakarta', country: 'Indonesia', longitude: 106.85, latitude: -6.21 },
  { capital: 'Tehran', country: 'Iran', longitude: 51.39, latitude: 35.69 },
  { capital: 'Baghdad', country: 'Iraq', longitude: 44.37, latitude: 33.31 },
  { capital: 'Dublin', country: 'Ireland', longitude: -6.27, latitude: 53.35 },
  { capital: 'Jerusalem', country: 'Israel', longitude: 35.22, latitude: 31.77 },
  { capital: 'Rome', country: 'Italy', longitude: 12.5, latitude: 41.89 },
  { capital: 'Kingston', country: 'Jamaica', longitude: -76.79, latitude: 18.0 },
  { capital: 'Tokyo', country: 'Japan', longitude: 139.69, latitude: 35.69 },
  { capital: 'Amman', country: 'Jordan', longitude: 35.93, latitude: 31.95 },
  { capital: 'Astana', country: 'Kazakhstan', longitude: 71.43, latitude: 51.17 },
  { capital: 'Nairobi', country: 'Kenya', longitude: 36.82, latitude: -1.29 },
  { capital: 'Tarawa', country: 'Kiribati', longitude: 172.98, latitude: 1.45 },
  { capital: 'Kuwait City', country: 'Kuwait', longitude: 47.98, latitude: 29.37 },
  { capital: 'Bishkek', country: 'Kyrgyzstan', longitude: 74.59, latitude: 42.87 },
  { capital: 'Vientiane', country: 'Laos', longitude: 102.63, latitude: 17.97 },
  { capital: 'Riga', country: 'Latvia', longitude: 24.11, latitude: 56.95 },
  { capital: 'Beirut', country: 'Lebanon', longitude: 35.5, latitude: 33.89 },
  { capital: 'Maseru', country: 'Lesotho', longitude: 27.48, latitude: -29.31 },
  { capital: 'Monrovia', country: 'Liberia', longitude: -10.8, latitude: 6.3 },
  { capital: 'Tripoli', country: 'Libya', longitude: 13.18, latitude: 32.9 },
  { capital: 'Vaduz', country: 'Liechtenstein', longitude: 9.52, latitude: 47.14 },
  { capital: 'Vilnius', country: 'Lithuania', longitude: 25.28, latitude: 54.69 },
  { capital: 'Luxembourg', country: 'Luxembourg', longitude: 6.13, latitude: 49.61 },
  { capital: 'Antananarivo', country: 'Madagascar', longitude: 47.52, latitude: -18.91 },
  { capital: 'Lilongwe', country: 'Malawi', longitude: 33.79, latitude: -13.97 },
  { capital: 'Kuala Lumpur', country: 'Malaysia', longitude: 101.69, latitude: 3.14 },
  { capital: 'Malé', country: 'Maldives', longitude: 73.51, latitude: 4.18 },
  { capital: 'Bamako', country: 'Mali', longitude: -8.0, latitude: 12.65 },
  { capital: 'Valletta', country: 'Malta', longitude: 14.51, latitude: 35.9 },
  { capital: 'Majuro', country: 'Marshall Islands', longitude: 171.38, latitude: 7.09 },
  { capital: 'Nouakchott', country: 'Mauritania', longitude: -15.98, latitude: 18.09 },
  { capital: 'Port Louis', country: 'Mauritius', longitude: 57.5, latitude: -20.16 },
  { capital: 'Mexico City', country: 'Mexico', longitude: -99.13, latitude: 19.43 },
  { capital: 'Palikir', country: 'Micronesia', longitude: 158.15, latitude: 6.92 },
  { capital: 'Chișinău', country: 'Moldova', longitude: 28.83, latitude: 47.01 },
  { capital: 'Monaco', country: 'Monaco', longitude: 7.42, latitude: 43.73 },
  { capital: 'Ulaanbaatar', country: 'Mongolia', longitude: 106.91, latitude: 47.92 },
  { capital: 'Podgorica', country: 'Montenegro', longitude: 19.26, latitude: 42.44 },
  { capital: 'Rabat', country: 'Morocco', longitude: -6.84, latitude: 34.01 },
  { capital: 'Maputo', country: 'Mozambique', longitude: 32.59, latitude: -25.97 },
  { capital: 'Naypyidaw', country: 'Myanmar', longitude: 96.13, latitude: 19.76 },
  { capital: 'Windhoek', country: 'Namibia', longitude: 17.08, latitude: -22.57 },
  { capital: 'Yaren', country: 'Nauru', longitude: 166.92, latitude: -0.55 },
  { capital: 'Kathmandu', country: 'Nepal', longitude: 85.32, latitude: 27.72 },
  { capital: 'Amsterdam', country: 'Netherlands', longitude: 4.9, latitude: 52.37 },
  { capital: 'Wellington', country: 'New Zealand', longitude: 174.78, latitude: -41.29 },
  { capital: 'Managua', country: 'Nicaragua', longitude: -86.25, latitude: 12.15 },
  { capital: 'Niamey', country: 'Niger', longitude: 2.11, latitude: 13.51 },
  { capital: 'Abuja', country: 'Nigeria', longitude: 7.49, latitude: 9.06 },
  { capital: 'Pyongyang', country: 'North Korea', longitude: 125.75, latitude: 39.02 },
  { capital: 'Skopje', country: 'North Macedonia', longitude: 21.43, latitude: 42.0 },
  { capital: 'Oslo', country: 'Norway', longitude: 10.75, latitude: 59.91 },
  { capital: 'Muscat', country: 'Oman', longitude: 58.39, latitude: 23.61 },
  { capital: 'Islamabad', country: 'Pakistan', longitude: 73.04, latitude: 33.69 },
  { capital: 'Ngerulmud', country: 'Palau', longitude: 134.62, latitude: 7.5 },
  { capital: 'Panama City', country: 'Panama', longitude: -79.52, latitude: 8.98 },
  { capital: 'Port Moresby', country: 'Papua New Guinea', longitude: 147.18, latitude: -6.31 },
  { capital: 'Asunción', country: 'Paraguay', longitude: -57.64, latitude: -25.28 },
  { capital: 'Lima', country: 'Peru', longitude: -77.04, latitude: -12.05 },
  { capital: 'Manila', country: 'Philippines', longitude: 120.98, latitude: 14.59 },
  { capital: 'Warsaw', country: 'Poland', longitude: 21.01, latitude: 52.23 },
  { capital: 'Lisbon', country: 'Portugal', longitude: -9.14, latitude: 38.72 },
  { capital: 'Doha', country: 'Qatar', longitude: 51.53, latitude: 25.29 },
  { capital: 'Bucharest', country: 'Romania', longitude: 26.1, latitude: 44.43 },
  { capital: 'Moscow', country: 'Russia', longitude: 37.62, latitude: 55.76 },
  { capital: 'Kigali', country: 'Rwanda', longitude: 29.87, latitude: -1.94 },
  { capital: 'Basseterre', country: 'Saint Kitts and Nevis', longitude: -62.72, latitude: 17.3 },
  { capital: 'Castries', country: 'Saint Lucia', longitude: -61.0, latitude: 14.01 },
  { capital: 'Kingstown', country: 'Saint Vincent and the Grenadines', longitude: -61.23, latitude: 13.16 },
  { capital: 'Apia', country: 'Samoa', longitude: -171.76, latitude: -13.83 },
  { capital: 'San Marino', country: 'San Marino', longitude: 12.45, latitude: 43.94 },
  { capital: 'São Tomé', country: 'São Tomé and Príncipe', longitude: 6.73, latitude: 0.34 },
  { capital: 'Riyadh', country: 'Saudi Arabia', longitude: 46.72, latitude: 24.69 },
  { capital: 'Dakar', country: 'Senegal', longitude: -17.44, latitude: 14.69 },
  { capital: 'Belgrade', country: 'Serbia', longitude: 20.46, latitude: 44.79 },
  { capital: 'Victoria', country: 'Seychelles', longitude: 55.45, latitude: -4.62 },
  { capital: 'Freetown', country: 'Sierra Leone', longitude: -13.23, latitude: 8.48 },
  { capital: 'Singapore', country: 'Singapore', longitude: 103.85, latitude: 1.29 },
  { capital: 'Bratislava', country: 'Slovakia', longitude: 17.11, latitude: 48.15 },
  { capital: 'Ljubljana', country: 'Slovenia', longitude: 14.51, latitude: 46.06 },
  { capital: 'Honiara', country: 'Solomon Islands', longitude: 159.95, latitude: -9.43 },
  { capital: 'Mogadishu', country: 'Somalia', longitude: 45.34, latitude: 2.05 },
  { capital: 'Pretoria', country: 'South Africa', longitude: 28.19, latitude: -25.75 },
  { capital: 'Seoul', country: 'South Korea', longitude: 126.98, latitude: 37.57 },
  { capital: 'Juba', country: 'South Sudan', longitude: 31.6, latitude: 4.85 },
  { capital: 'Madrid', country: 'Spain', longitude: -3.7, latitude: 40.42 },
  { capital: 'Sri Jayawardenepura Kotte', country: 'Sri Lanka', longitude: 79.89, latitude: 6.89 },
  { capital: 'Khartoum', country: 'Sudan', longitude: 32.53, latitude: 15.6 },
  { capital: 'Paramaribo', country: 'Suriname', longitude: -55.17, latitude: 5.84 },
  { capital: 'Stockholm', country: 'Sweden', longitude: 18.07, latitude: 59.33 },
  { capital: 'Bern', country: 'Switzerland', longitude: 7.45, latitude: 46.95 },
  { capital: 'Damascus', country: 'Syria', longitude: 36.29, latitude: 33.51 },
  { capital: 'Dushanbe', country: 'Tajikistan', longitude: 68.77, latitude: 38.56 },
  { capital: 'Dodoma', country: 'Tanzania', longitude: 35.74, latitude: -6.16 },
  { capital: 'Bangkok', country: 'Thailand', longitude: 100.5, latitude: 13.76 },
  { capital: 'Dili', country: 'Timor-Leste', longitude: 125.57, latitude: -8.56 },
  { capital: 'Lomé', country: 'Togo', longitude: 1.21, latitude: 6.14 },
  { capital: "Nuku'alofa", country: 'Tonga', longitude: -175.2, latitude: -21.21 },
  { capital: 'Port of Spain', country: 'Trinidad and Tobago', longitude: -61.52, latitude: 10.66 },
  { capital: 'Tunis', country: 'Tunisia', longitude: 10.18, latitude: 36.81 },
  { capital: 'Ankara', country: 'Türkiye', longitude: 32.87, latitude: 39.93 },
  { capital: 'Ashgabat', country: 'Turkmenistan', longitude: 58.38, latitude: 37.95 },
  { capital: 'Funafuti', country: 'Tuvalu', longitude: 179.2, latitude: -8.52 },
  { capital: 'Kampala', country: 'Uganda', longitude: 32.58, latitude: 0.31 },
  { capital: 'Kyiv', country: 'Ukraine', longitude: 30.52, latitude: 50.45 },
  { capital: 'Abu Dhabi', country: 'United Arab Emirates', longitude: 54.37, latitude: 24.45 },
  { capital: 'London', country: 'United Kingdom', longitude: -0.13, latitude: 51.51 },
  { capital: 'Washington, D.C.', country: 'United States', longitude: -77.04, latitude: 38.91 },
  { capital: 'Montevideo', country: 'Uruguay', longitude: -56.16, latitude: -34.88 },
  { capital: 'Tashkent', country: 'Uzbekistan', longitude: 69.28, latitude: 41.3 },
  { capital: 'Port Vila', country: 'Vanuatu', longitude: 168.32, latitude: -17.73 },
  { capital: 'Caracas', country: 'Venezuela', longitude: -66.9, latitude: 10.49 },
  { capital: 'Hanoi', country: 'Vietnam', longitude: 105.85, latitude: 21.03 },
  { capital: 'Sanaa', country: 'Yemen', longitude: 44.21, latitude: 15.37 },
  { capital: 'Lusaka', country: 'Zambia', longitude: 28.28, latitude: -15.39 },
  { capital: 'Harare', country: 'Zimbabwe', longitude: 31.05, latitude: -17.83 },
];
