export interface Capital {
  capital: string;
  country: string;
  longitude: number;
  latitude: number;
}

export const CAPITALS: Capital[] = [
  {
    capital: 'Kabul',
    country: 'Afghanistan',
    longitude: 69.17,
    latitude: 34.53,
  },
  { capital: 'Tirana', country: 'Albania', longitude: 19.82, latitude: 41.33 },
  { capital: 'Algiers', country: 'Algeria', longitude: 3.04, latitude: 36.77 },
  { capital: 'Luanda', country: 'Angola', longitude: 13.23, latitude: -8.84 },
  {
    capital: 'Buenos Aires',
    country: 'Argentina',
    longitude: -58.38,
    latitude: -34.6,
  },
  { capital: 'Yerevan', country: 'Armenia', longitude: 44.51, latitude: 40.18 },
  {
    capital: 'Canberra',
    country: 'Australia',
    longitude: 149.13,
    latitude: -35.28,
  },
  { capital: 'Vienna', country: 'Austria', longitude: 16.37, latitude: 48.21 },
  { capital: 'Baku', country: 'Azerbaijan', longitude: 49.87, latitude: 40.41 },
  {
    capital: 'Dhaka',
    country: 'Bangladesh',
    longitude: 90.41,
    latitude: 23.71,
  },
  { capital: 'Minsk', country: 'Belarus', longitude: 27.57, latitude: 53.9 },
  { capital: 'Brussels', country: 'Belgium', longitude: 4.35, latitude: 50.85 },
  {
    capital: 'Brasília',
    country: 'Brazil',
    longitude: -47.88,
    latitude: -15.79,
  },
  { capital: 'Sofia', country: 'Bulgaria', longitude: 23.32, latitude: 42.7 },
  {
    capital: 'Phnom Penh',
    country: 'Cambodia',
    longitude: 104.92,
    latitude: 11.56,
  },
  { capital: 'Yaoundé', country: 'Cameroon', longitude: 11.52, latitude: 3.87 },
  { capital: 'Ottawa', country: 'Canada', longitude: -75.7, latitude: 45.42 },
  {
    capital: 'Santiago',
    country: 'Chile',
    longitude: -70.67,
    latitude: -33.45,
  },
  { capital: 'Beijing', country: 'China', longitude: 116.41, latitude: 39.9 },
  { capital: 'Bogotá', country: 'Colombia', longitude: -74.07, latitude: 4.71 },
  {
    capital: 'Kinshasa',
    country: 'DR Congo',
    longitude: 15.27,
    latitude: -4.32,
  },
  {
    capital: 'San José',
    country: 'Costa Rica',
    longitude: -84.09,
    latitude: 9.93,
  },
  { capital: 'Zagreb', country: 'Croatia', longitude: 15.98, latitude: 45.81 },
  { capital: 'Havana', country: 'Cuba', longitude: -82.37, latitude: 23.11 },
  { capital: 'Prague', country: 'Czechia', longitude: 14.42, latitude: 50.08 },
  {
    capital: 'Copenhagen',
    country: 'Denmark',
    longitude: 12.57,
    latitude: 55.68,
  },
  { capital: 'Quito', country: 'Ecuador', longitude: -78.47, latitude: -0.18 },
  { capital: 'Cairo', country: 'Egypt', longitude: 31.24, latitude: 30.04 },
  {
    capital: 'Addis Ababa',
    country: 'Ethiopia',
    longitude: 38.75,
    latitude: 9.02,
  },
  {
    capital: 'Helsinki',
    country: 'Finland',
    longitude: 24.94,
    latitude: 60.17,
  },
  { capital: 'Paris', country: 'France', longitude: 2.35, latitude: 48.86 },
  { capital: 'Berlin', country: 'Germany', longitude: 13.41, latitude: 52.52 },
  { capital: 'Accra', country: 'Ghana', longitude: -0.19, latitude: 5.56 },
  { capital: 'Athens', country: 'Greece', longitude: 23.73, latitude: 37.98 },
  {
    capital: 'Guatemala City',
    country: 'Guatemala',
    longitude: -90.53,
    latitude: 14.63,
  },
  { capital: 'New Delhi', country: 'India', longitude: 77.21, latitude: 28.61 },
  {
    capital: 'Jakarta',
    country: 'Indonesia',
    longitude: 106.85,
    latitude: -6.21,
  },
  { capital: 'Tehran', country: 'Iran', longitude: 51.39, latitude: 35.69 },
  { capital: 'Baghdad', country: 'Iraq', longitude: 44.37, latitude: 33.31 },
  { capital: 'Dublin', country: 'Ireland', longitude: -6.27, latitude: 53.35 },
  {
    capital: 'Jerusalem',
    country: 'Israel',
    longitude: 35.22,
    latitude: 31.77,
  },
  { capital: 'Rome', country: 'Italy', longitude: 12.5, latitude: 41.89 },
  { capital: 'Tokyo', country: 'Japan', longitude: 139.69, latitude: 35.69 },
  { capital: 'Nairobi', country: 'Kenya', longitude: 36.82, latitude: -1.29 },
  {
    capital: 'Seoul',
    country: 'South Korea',
    longitude: 126.98,
    latitude: 37.57,
  },
  {
    capital: 'Kuwait City',
    country: 'Kuwait',
    longitude: 47.98,
    latitude: 29.37,
  },
  { capital: 'Beirut', country: 'Lebanon', longitude: 35.5, latitude: 33.89 },
  { capital: 'Tripoli', country: 'Libya', longitude: 13.18, latitude: 32.9 },
  {
    capital: 'Kuala Lumpur',
    country: 'Malaysia',
    longitude: 101.69,
    latitude: 3.14,
  },
  {
    capital: 'Mexico City',
    country: 'Mexico',
    longitude: -99.13,
    latitude: 19.43,
  },
  { capital: 'Rabat', country: 'Morocco', longitude: -6.84, latitude: 34.01 },
  {
    capital: 'Maputo',
    country: 'Mozambique',
    longitude: 32.59,
    latitude: -25.97,
  },
  {
    capital: 'Naypyidaw',
    country: 'Myanmar',
    longitude: 96.13,
    latitude: 19.76,
  },
  { capital: 'Kathmandu', country: 'Nepal', longitude: 85.32, latitude: 27.72 },
  {
    capital: 'Amsterdam',
    country: 'Netherlands',
    longitude: 4.9,
    latitude: 52.37,
  },
  {
    capital: 'Wellington',
    country: 'New Zealand',
    longitude: 174.78,
    latitude: -41.29,
  },
  { capital: 'Abuja', country: 'Nigeria', longitude: 7.49, latitude: 9.06 },
  { capital: 'Oslo', country: 'Norway', longitude: 10.75, latitude: 59.91 },
  {
    capital: 'Islamabad',
    country: 'Pakistan',
    longitude: 73.04,
    latitude: 33.69,
  },
  { capital: 'Lima', country: 'Peru', longitude: -77.04, latitude: -12.05 },
  {
    capital: 'Manila',
    country: 'Philippines',
    longitude: 120.98,
    latitude: 14.59,
  },
  { capital: 'Warsaw', country: 'Poland', longitude: 21.01, latitude: 52.23 },
  { capital: 'Lisbon', country: 'Portugal', longitude: -9.14, latitude: 38.72 },
  {
    capital: 'Bucharest',
    country: 'Romania',
    longitude: 26.1,
    latitude: 44.43,
  },
  { capital: 'Moscow', country: 'Russia', longitude: 37.62, latitude: 55.76 },
  {
    capital: 'Riyadh',
    country: 'Saudi Arabia',
    longitude: 46.72,
    latitude: 24.69,
  },
  { capital: 'Dakar', country: 'Senegal', longitude: -17.44, latitude: 14.69 },
  { capital: 'Belgrade', country: 'Serbia', longitude: 20.46, latitude: 44.79 },
  {
    capital: 'Singapore',
    country: 'Singapore',
    longitude: 103.85,
    latitude: 1.29,
  },
  {
    capital: 'Pretoria',
    country: 'South Africa',
    longitude: 28.19,
    latitude: -25.75,
  },
  { capital: 'Madrid', country: 'Spain', longitude: -3.7, latitude: 40.42 },
  {
    capital: 'Colombo',
    country: 'Sri Lanka',
    longitude: 79.86,
    latitude: 6.93,
  },
  {
    capital: 'Stockholm',
    country: 'Sweden',
    longitude: 18.07,
    latitude: 59.33,
  },
  { capital: 'Bern', country: 'Switzerland', longitude: 7.45, latitude: 46.95 },
  { capital: 'Damascus', country: 'Syria', longitude: 36.29, latitude: 33.51 },
  {
    capital: 'Bangkok',
    country: 'Thailand',
    longitude: 100.5,
    latitude: 13.76,
  },
  { capital: 'Tunis', country: 'Tunisia', longitude: 10.18, latitude: 36.81 },
  { capital: 'Ankara', country: 'Turkey', longitude: 32.87, latitude: 39.93 },
  { capital: 'Kyiv', country: 'Ukraine', longitude: 30.52, latitude: 50.45 },
  { capital: 'Abu Dhabi', country: 'UAE', longitude: 54.37, latitude: 24.45 },
  {
    capital: 'London',
    country: 'United Kingdom',
    longitude: -0.13,
    latitude: 51.51,
  },
  {
    capital: 'Washington, D.C.',
    country: 'United States',
    longitude: -77.04,
    latitude: 38.91,
  },
  {
    capital: 'Montevideo',
    country: 'Uruguay',
    longitude: -56.16,
    latitude: -34.88,
  },
  { capital: 'Hanoi', country: 'Vietnam', longitude: 105.85, latitude: 21.03 },
  { capital: 'Lusaka', country: 'Zambia', longitude: 28.28, latitude: -15.39 },
  {
    capital: 'Harare',
    country: 'Zimbabwe',
    longitude: 31.05,
    latitude: -17.83,
  },
];
